import { ReproductionStep, RegressionTest, CrashReport } from '../types/reprox';

export function generateEspressoTest(report: CrashReport, steps: ReproductionStep[]): RegressionTest {
  const sanitizeName = (str: string) => str.replace(/[^a-zA-Z0-9]/g, '');
  const testName = `test_reproduce_${sanitizeName(report.errorType)}_${Date.now().toString().slice(-4)}`;

  const espressoActions = steps.map(step => {
    // Determine friendly target text or ID
    let actionCode = '';
    const desc = step.action;

    if (desc.toLowerCase().includes('open ') || desc.toLowerCase().includes('navigated')) {
      const screen = desc.replace(/open /i, '').replace(/navigated to /i, '').trim();
      actionCode = `    // Step ${step.stepNumber}: Navigate to ${screen}\n    onView(withText("${screen}")).perform(click())`;
    } else if (desc.toLowerCase().includes('add to cart') || desc.toLowerCase().includes('added')) {
      actionCode = `    // Step ${step.stepNumber}: Add item to cart\n    onView(withText("Add to Cart")).perform(click())`;
    } else if (desc.toLowerCase().includes('upi') || desc.toLowerCase().includes('card') || desc.toLowerCase().includes('payment method')) {
      actionCode = `    // Step ${step.stepNumber}: Select payment method\n    onView(withText("${desc.replace('Selected ', '')}")).perform(click())`;
    } else if (desc.toLowerCase().includes('pay')) {
      actionCode = `    // Step ${step.stepNumber}: Trigger payment button\n    onView(withId(R.id.btn_pay)).perform(click())`;
    } else {
      actionCode = `    // Step ${step.stepNumber}: ${desc}\n    onView(withText("${desc}")).perform(click())`;
    }

    return actionCode;
  }).join('\n\n');

  const code = `package com.reprox.coffee.regression

import androidx.test.ext.junit.rules.ActivityScenarioRule
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.espresso.Espresso.onView
import androidx.test.espresso.action.ViewActions.click
import androidx.test.espresso.matcher.ViewMatchers.withId
import androidx.test.espresso.matcher.ViewMatchers.withText
import androidx.test.espresso.matcher.ViewMatchers.isDisplayed
import androidx.test.espresso.assertion.ViewAssertions.matches
import com.reprox.coffee.MainActivity
import com.reprox.coffee.R
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

/**
 * AUTO-GENERATED BY REPROX REGRESSION TEST GENERATOR
 * Source Crash: ${report.errorType} in ${report.screen}
 * Date: ${report.timestamp}
 */
@RunWith(AndroidJUnit4::class)
class ${sanitizeName(report.errorType)}RegressionTest {

    @get:Rule
    val activityRule = ActivityScenarioRule(MainActivity::class.java)

    @Test
    fun ${testName}() {
${espressoActions}

        // Assert that the app remains stable and does not throw ${report.errorType}
        onView(withId(R.id.checkout_root))
            .check(matches(isDisplayed()))
    }
}`;

  return {
    framework: 'Espresso',
    language: 'kotlin',
    testName,
    code,
  };
}

export function generateComposeTest(report: CrashReport, steps: ReproductionStep[]): RegressionTest {
  const sanitizeName = (str: string) => str.replace(/[^a-zA-Z0-9]/g, '');
  const testName = `reproduce${sanitizeName(report.errorType)}Flow`;

  const composeActions = steps.map(step => {
    let actionCode = '';
    const desc = step.action;
    if (desc.toLowerCase().includes('open ') || desc.toLowerCase().includes('navigated')) {
      const screen = desc.replace(/open /i, '').replace(/navigated to /i, '').trim();
      actionCode = `        // Step ${step.stepNumber}: Open ${screen}\n        composeTestRule.onNodeWithText("${screen}").performClick()`;
    } else if (desc.toLowerCase().includes('pay')) {
      actionCode = `        // Step ${step.stepNumber}: Trigger Pay CTA\n        composeTestRule.onNodeWithTag("pay_button").performClick()`;
    } else {
      actionCode = `        // Step ${step.stepNumber}: ${desc}\n        composeTestRule.onNodeWithText("${desc}").performClick()`;
    }
    return actionCode;
  }).join('\n\n');

  const code = `package com.reprox.coffee.compose

import androidx.compose.ui.test.*
import androidx.compose.ui.test.junit4.createAndroidComposeRule
import com.reprox.coffee.MainActivity
import org.junit.Rule
import org.junit.Test

/**
 * AUTO-GENERATED BY REPROX REGRESSION TEST GENERATOR (Jetpack Compose)
 * Target Screen: ${report.screen}
 * Error: ${report.errorType}
 */
class ${sanitizeName(report.errorType)}ComposeTest {

    @get:Rule
    val composeTestRule = createAndroidComposeRule<MainActivity>()

    @Test
    fun ${testName}() {
${composeActions}

        // Verify state resilience - screen does not crash
        composeTestRule.onNodeWithTag("error_banner")
            .assertDoesNotExist()
    }
}`;

  return {
    framework: 'Compose UI',
    language: 'kotlin',
    testName,
    code,
  };
}
