import React, { useState } from 'react';
import { useInvestigation } from '../context/InvestigationContext';
import { Download, Copy, Check, FileText } from 'lucide-react';

export const DeveloperReportView: React.FC = () => {
  const { activeCrash, analysis, resetDemo } = useInvestigation();
  const [copied, setCopied] = useState(false);

  if (!activeCrash || !analysis) {
    return <div className="p-8 text-white">No analysis context available.</div>;
  }

  const generateMarkdown = () => {
    return `# ReproX Exhaustive Crash Diagnostic Report
**Crash ID**: ${activeCrash.id}
**Investigation ID**: ${analysis.investigationId || 'N/A'}
**Timestamp**: ${activeCrash.timestamp}

---

## 1. Crash Summary
- **Exception**: \`${activeCrash.errorType}\`
- **Message**: ${activeCrash.message}
- **Severity**: ${analysis.severity}

## 2. Triggering Action
${analysis.triggeringAction}

## 3. Application State Snapshot
- **Screen**: ${activeCrash.screen}
- **Component**: \`${activeCrash.method || analysis.affectedComponent}\`

## 4. Device Context
- **Model**: ${activeCrash.deviceContext.deviceModel}
- **OS Version**: ${activeCrash.deviceContext.osVersion}

## 5. Environment Context
- **App Version**: ${activeCrash.deviceContext.appVersion}
- **Build Number**: ${activeCrash.deviceContext.buildNumber}

## 6. Resource State
- **Memory Usage**: ${activeCrash.deviceContext.memoryUsageMb}MB / ${activeCrash.deviceContext.totalMemoryMb}MB
- **Battery**: ${activeCrash.deviceContext.batteryLevelPercent}%

## 7. Network State
- **Status**: ${activeCrash.deviceContext.networkStatus}

## 8. Stack Trace
\`\`\`java
${activeCrash.stackTrace?.split('\n').slice(0, 10).join('\n') || 'No stack trace available'}
\`\`\`

## 9. Last 15 User Actions
${activeCrash.recentActions?.slice(-15).map((action, index) => `${index + 1}. [${action.timestamp}] ${action.type}: ${action.description}`).join('\n') || 'No actions recorded.'}

## 10. Initial AI Inference
${analysis.likelyRootCause}

## 11. Root Cause
${analysis.whyItHappened}

## 12. Expected Behavior
${analysis.whatShouldHaveHappened}

## 13. Risk Analysis
- **Risk Level**: ${analysis.riskLevel}
- **Confidence**: ${analysis.confidenceScore}%

## 14. Auto-Debug Eligibility
Eligible: ${analysis.autoDebugEligible ? 'Yes' : 'No (Requires Manual Intervention)'}

## 15. Exact Location (File)
\`${analysis.changeLocation?.file || 'N/A'}\`

## 16. Exact Location (Line)
Line: ${analysis.changeLocation?.line || 'N/A'}

## 17. Code Snippet Context
\`\`\`typescript
${analysis.changeLocation?.snippet || 'Code snippet not available'}
\`\`\`

## 18. Match Confidence
${analysis.changeLocation?.isConfirmed ? 'CONFIRMED MATCH' : 'INFERRED'}

## 19. Evidence Chain - Step 1
${analysis.evidenceChain[0] || 'N/A'}

## 20. Evidence Chain - Step 2
${analysis.evidenceChain[1] || 'N/A'}

## 21. How to Solve
${analysis.suggestedFix.explanation}

## 22. Alternative Solution A
${analysis.possibleSolutions?.[0]?.title || 'N/A'} - ${analysis.possibleSolutions?.[0]?.description || ''}

## 23. Alternative Solution B
${analysis.possibleSolutions?.[1]?.title || 'N/A'} - ${analysis.possibleSolutions?.[1]?.description || ''}

## 24. Alternative Solution C
${analysis.possibleSolutions?.[2]?.title || 'N/A'} - ${analysis.possibleSolutions?.[2]?.description || ''}

## 25. Proposed Patch (Diff)
\`\`\`diff
${analysis.suggestedFix.diffSnippet || 'No diff available'}
\`\`\`

## 26. Proposed Patch (Full Code)
\`\`\`typescript
${analysis.suggestedFix.codeSnippet || 'No code available'}
\`\`\`

## 27. Regression Test Framework
${activeCrash.deviceContext.os === 'Android' ? 'Espresso / Compose UI' : 'XCTest'}

## 28. Synthesized Regression Test
\`\`\`kotlin
@Test
fun testCrashPrevention() {
    // Generated by AI
}
\`\`\`

## 29. Prevention Recommendations
${analysis.preventionRecommendation.join('\n- ')}

## 30. Telemetry Tags
${JSON.stringify(activeCrash.tags || {})}

## 31. Investigation Session Data
Stored in Session Storage under \`reprox_investigation\`

## 32. Next Steps
Review the patch and apply it manually.

## 33. Developer Checklist
- [ ] Review Stack Trace
- [ ] Read Root Cause
- [ ] Validate Alternatives
- [ ] Apply Patch
- [ ] Run Regression Test
`;
  };

  const markdownContent = generateMarkdown();

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement('a');
    const file = new Blob([markdownContent], { type: 'text/markdown' });
    element.href = URL.createObjectURL(file);
    element.download = `reprox_report_${activeCrash.id}.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="max-w-4xl mx-auto py-8 animate-fadeIn space-y-6">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight flex items-center gap-2">
            <FileText className="w-6 h-6 text-cyan-500" />
            Exhaustive Developer Report
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            The AI could not automatically debug this issue. Please review the 33-point manual report.
          </p>
        </div>
        <button
          onClick={resetDemo}
          className="text-xs text-slate-400 hover:text-white underline"
        >
          Close Session
        </button>
      </div>

      <div className="bg-dark-900 border border-slate-700 rounded-xl shadow-2xl flex flex-col overflow-hidden max-h-[70vh]">
        <div className="flex-1 overflow-y-auto p-6 bg-dark-950/50">
          <pre className="text-[11px] font-mono text-slate-300 leading-relaxed whitespace-pre-wrap">
            {markdownContent}
          </pre>
        </div>

        <div className="px-5 py-4 border-t border-slate-700 bg-dark-950 flex justify-end gap-3 shrink-0">
          <button
            onClick={handleCopy}
            className="px-4 py-2 rounded-lg font-bold text-xs bg-slate-800 hover:bg-slate-700 text-white flex items-center gap-2 transition-colors border border-slate-700"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied' : 'Copy Markdown'}
          </button>
          
          <button
            onClick={handleDownload}
            className="px-4 py-2 rounded-lg font-bold text-xs bg-cyan-500 hover:bg-cyan-400 text-dark-950 flex items-center gap-2 transition-colors shadow-lg shadow-cyan-500/20"
          >
            <Download className="w-4 h-4" />
            Download .md
          </button>
        </div>
      </div>
    </div>
  );
};
