import React, { useState } from 'react';
import { X, Download, Copy, Check, FileText } from 'lucide-react';
import { AnalysisResult, CrashReport } from '../types/reprox';

interface DeveloperReportModalProps {
  report: CrashReport;
  analysis: AnalysisResult;
  onClose: () => void;
}

export const DeveloperReportModal: React.FC<DeveloperReportModalProps> = ({
  report,
  analysis,
  onClose
}) => {
  const [copied, setCopied] = useState(false);

  const generateMarkdown = () => {
    return `# ReproX Automated Crash Report
**Crash ID**: ${report.id}
**Timestamp**: ${report.timestamp}
**Device**: ${report.deviceContext.deviceModel} (OS: ${report.deviceContext.osVersion})
**App Version**: ${report.deviceContext.appVersion} (${report.deviceContext.buildNumber})

---

## 1. Crash Summary
- **Exception**: \`${report.errorType}\`
- **Message**: ${report.message}
- **Screen**: ${report.screen}
- **Component**: \`${report.method || analysis.affectedComponent}\`
- **Severity**: ${analysis.severity}

---

## 2. AI Investigation
**Root Cause**:
${analysis.likelyRootCause}

**Why it happened**:
${analysis.whyItHappened}

**What should have happened**:
${analysis.whatShouldHaveHappened}

**Triggering Action**:
${analysis.triggeringAction}

**Evidence Chain**:
${analysis.evidenceChain.map(e => `- [x] ${e}`).join('\n')}

---

## 3. Reproduction Steps
${analysis.reproductionSteps.map(step => `${step.stepNumber}. ${step.action} (Screen: ${step.screen})`).join('\n')}

---

## 4. Suggested Fix
**Title**: ${analysis.suggestedFix.title}
**Explanation**: ${analysis.suggestedFix.explanation}

\`\`\`${analysis.suggestedFix.language}
// ${analysis.suggestedFix.filePath}
${analysis.suggestedFix.codeSnippet}
\`\`\`

---

## 5. Prevention & Regression
**Recommendations**:
${analysis.preventionRecommendation.map(r => `- ${r}`).join('\n')}

**Status**: [ ] Fixed  [ ] Verified
*Generated by ReproX AI Investigation Engine*
`;
  };

  const markdownContent = generateMarkdown();

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement('a');
    const file = new Blob([markdownContent], { type: 'text/markdown' });
    element.href = URL.createObjectURL(file);
    element.download = `reprox_report_${report.id}.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn">
      <div 
        className="w-full max-w-4xl bg-dark-900 border border-slate-700 rounded-xl shadow-2xl flex flex-col overflow-hidden max-h-[90vh]"
        onClick={e => e.stopPropagation()}
      >
        <div className="px-5 py-4 border-b border-slate-700 bg-dark-950 flex justify-between items-center shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-cyan-500/20 border border-cyan-500/40 flex items-center justify-center text-cyan-400">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-white uppercase tracking-wider">
                Developer Report
              </h2>
              <p className="text-xs text-slate-400">Structured markdown export for Jira / GitHub Issues</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-2 rounded-lg hover:bg-slate-800 text-slate-400 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-6 bg-dark-950/50">
          <pre className="text-xs font-mono text-slate-300 leading-relaxed whitespace-pre-wrap">
            {markdownContent}
          </pre>
        </div>

        <div className="px-5 py-4 border-t border-slate-700 bg-dark-950 flex justify-end gap-3 shrink-0">
          <button
            onClick={handleCopy}
            className="px-4 py-2 rounded-lg font-bold text-xs bg-slate-800 hover:bg-slate-700 text-white flex items-center gap-2 transition-colors border border-slate-700"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied to Clipboard' : 'Copy Markdown'}
          </button>
          
          <button
            onClick={handleDownload}
            className="px-4 py-2 rounded-lg font-bold text-xs bg-cyan-500 hover:bg-cyan-400 text-dark-950 flex items-center gap-2 transition-colors shadow-lg shadow-cyan-500/20"
          >
            <Download className="w-4 h-4" />
            Download .md
          </button>
        </div>
      </div>
    </div>
  );
};
